# Generated by Django 3.2.9 on 2021-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('tweets', models.CharField(choices=[], max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
            ],
        ),
    ]
